name: ingress-nginx
title: Ingress Nginx
type: infrastructure
icon: nginx
scalable: false
hostname: ingress-nginx
containers:
  - name: controller
annotations:
- name: proxy-buffer-size
  value: 32k
- name: proxy-body-size
  value: '0'
- name: annotations-risk-level
  value: Critical
  
helm:
  name: ingress-nginx
  source: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.13.2
  configurations:
  - container: controller
    annotations: controller.config
    labels: controller.labels
    resources: controller.resources    
  values: 
# to set default no-indexation headers via 'configuration-snippet'  
  - name: controller.allowSnippetAnnotations
    value: true
