name: ingress-nginx
title: Ingress Nginx
type: infrastructure
icon: nginx
scalable: false
hostname: ingress-nginx
containers:
  - name: controller
annotations:
- name: proxy-buffer-size
  value: 32k
- name: proxy-body-size
  value: '0'
- name: use-proxy-protocol
  value: 'true'
# to set default no-indexation headers via 'configuration-snippet'
- name: allow-snippet-annotations
  value: 'true'
  
